### PR TITLE
add `nodeBlockForRowAtIndexPath` support

### PR DESCRIPTION
**Pull request by fumito-ito**
fallback to `nodeForRowAtIndexPath` if nodeBlock is not defined by constructor.

### CODE REVIEW

**Comment by dangthaison91** [comment]
@fumito-ito Thanks for your PR and sorry for the delay.

Can we use both **nodeForRow** and **nodeBlockForRow** ? If no, should we create another init construction for each to help other users avoid implement both closures by mistake?

**Comment by fumito-ito** [comment]
@dangthaison91 

> Can we use both nodeForRow and nodeBlockForRow ?

No. According to [API docs](http://texturegroup.org/appledoc/Protocols/ASTableDataSource.html#//api/name/tableNode:nodeBlockForRowAtIndexPath:), `nodeBlockForRow ` takes precedence over `tableNode:nodeForRowAtIndexPath:` if implemented. 

> If no, should we create another init construction for each to help other users avoid implement both closures by mistake?

I think so too ! I will implement this PR in this weekend.

**Comment by dangthaison91** [comment]
Hi @fumito-ito, have any progress on this PR? I'm really looking forward to merging it.

**Comment by fumito-ito** [comment]
@dangthaison91 sorry for delay.

But I found my PR has already separated constructor for `nodeBlockForRow` and `nodeForRow`.
So I guess that users will not be able to implement both closure.

Do I understand you ? If no, Could you tell me more description ?

**Review by dangthaison91 — APPROVED** [review]

**Comment by dangthaison91** [comment]
@fumito-ito Oh really sorry, It's my mistake :D.

**Pull request merged**
