### PR TITLE
accept `nodeBlock*` delegates for ASCollectionNode

### PR DESCRIPTION
**Pull request by fumito-ito**
for #22 and nits for `ASBatchContext` delegate

### CODE REVIEW

**Review by dangthaison91 — APPROVED** [review]
LGTM. Thanks @fumito-ito

**Comment by vldalx** [comment]
@fumito-ito @dangthaison91 
Had you tested this PR before you merged it?

According to [ASTableDataSource docs](http://texturegroup.org/appledoc/Protocols/ASTableDataSource.html#//api/name/tableNode:nodeBlockForRowAtIndexPath:) `tableNode:nodeBlockForRowAtIndexPath:` method takes precedence over `tableNode:nodeForRowAtIndexPath:` if implemented.

According to the RP changes if `configureCellBlock` is not set then `configureCell` will be invoked from `tableNode:nodeBlockForRowAtIndexPath:` method. It means `configureCell` **can be called on the main thread or a background queue**. That is dead wrong.
Furthermore, two closures look redundant in that case.

**Comment by fumito-ito** [comment]
@vldalx thanks for your feedback.

> It means configureCell can be called on the main thread or a background queue. That is dead wrong.

Is #14 same as your feedback ?

> Furthermore, two closures look redundant in that case.

I cannot what you mean. Can you describe me more details for it ?

**Comment by vldalx** [comment]
@fumito-ito 
take a look at the code below. it has the similar logic to the RP changes.
``` Swift
class ASTableSectionedDataSource {
    var configureCell: ConfigureCell
    var configureCellBlock: ConfigureCellBlock?

    init(configureCell: @escaping ConfigureCell) {
        self.configureCell = configureCell
        self.configureCellBlock = nil
    }

    func tableNode(_ tableNode: ASTableNode, nodeForRowAt indexPath: IndexPath) -> ASCellNode {
        // never invoked.
        // configureCell is supposed to called here
    }

    func tableNode(_ tableNode: ASTableNode, nodeBlockForRowAt indexPath: IndexPath) -> ASCellNodeBlock {
        let closure = configureCellBlock ?? configureCell
        // configureCell can't be fallback here
        return closure(self, tableNode, indexPath, self[indexPath])
    }
}
```
taking into account that approach, why do we need two closures? That just shows something is wrong.

**Pull request merged**
